// angular-project/src/app/button-counter/button-counter.ts
import { Component, Input } from '@angular/core';
import { CustomText } from '../custom-text/custom-text';
import { CustomButton } from '../custom-button/custom-button';

@Component({
  selector: 'app-button-counter',
  imports: [CustomText, CustomButton],
  templateUrl: './button-counter.html',
  styleUrl: './button-counter.css',
})
export class ButtonCounter {
  @Input() name: string = '';
  count: number = 0;

  ngOnInit() {}

  getCountText(): string {
    return `Button ${this.name} count: ${this.count}`;
  }

  getButtonName(): string {
    return `Button ${this.name}`;
  }

  increaseCount = () => {
    this.count += 1;
  };
}

// react-project/src/components/button-counter/button-counter.js
import CustomText from '../custom-text/custom-text';
import CustomButton from '../custom-button/custom-button';
import { useState } from 'react';

function ButtonCounter(props) {
  const [count, setCount] = useState(0);
  return (
    <>
      <CustomText text={`Button ${props.name} count: ${count}`} />
      <CustomButton
        text={`Button ${props.name}`}
        onClick={() => {
          setCount(count + 1);
        }}
      />
    </>
  );
}

export default ButtonCounter;
